# This file is part of Sid.
# https://github.com/yoavram/Sid

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Yoav Ram <yoav@yoavram.com>

# This file is modified from https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - 2.7
notifications:
  email: 
    - yoav@yoavram.com

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes -q conda
  - conda config --add channels yoavram
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - pip install codecov

# Install packages
install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip requests conda-build jinja2 anaconda-client atlas numpy scipy matplotlib scikit-image pillow coverage nose sphinx
#  - conda build conda-recipe
#  - conda install --use-local curveball

# Run test
script:  
  - nosetests tests --with-coverage --cover-package=curveball

after_success:
# Code coverage
  - codecov
