# This file is part of Sid.
# https://github.com/yoavram/Sid

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Yoav Ram <yoav@yoavram.com>

# This file is modified from https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - 3.7
notifications:
  email: 
    - yoav@yoavram.com

# Setup anaconda
before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - pip install codecov

# Install packages
install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip requests numpy scipy matplotlib scikit-image click pillow coverage nose 
  - pip install watchdog twine
  - python setup.py install

# Run test
script:
  - take_cover --version
  - nosetests Sid/tests --with-coverage --cover-package=Sid

after_success:
# Code coverage
  - codecov

before_deploy:
# Install latest version of the docs packages
  - pip install --upgrade sphinx sphinx-rtd-theme

deploy:
# Deploy to pypi
  provider: pypi
  user: yoavram
  password:
    secure: V4fgfbd6NfIPyjPnfWWPOpAq1LtIarBZ4PLQhXSLuhOSi1THU/qdnpwtAzotE1uyMdrZNUU0lYx+8mezCeX3w+1eg7bQeXn6L5VH+vTYJQ/nSmELKeQO44ePKCQDTJFwyhunDIySieLhb87sHcoXGxT4JdRgVP32gVeOKVGH7a0=
  on:
    tags: true
    repo: yoavram/Sid
    branch: master
  distributions: "sdist bdist_wheel"