name: Sid
dependencies:
- alabaster=0.7.6=py27_0
- babel=2.1.1=py27_0
- colorama=0.3.3=py27_0
- coverage=4.0=py27_0
- decorator=4.0.4=py27_0
- docutils=0.12=py27_1
- jinja2=2.8=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np110py27_1
- networkx=1.10=py27_0
- nose=1.3.7=py27_0
- numpy=1.10.1=py27_0
- pillow=3.0.0=py27_0
- pip=7.1.2=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.10.4=py27_1
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.6=py27_0
- scikit-image=0.11.3=np110py27_0
- scipy=0.16.0=np110py27_0
- setuptools=18.4=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- wheel=0.26.0=py27_1
- pip:
  - argh==0.26.1
  - click==5.1
  - funcsigs==0.4
  - mock==1.3.0
  - pathtools==0.1.2
  - pbr==1.8.1
  - pkginfo==1.2.1
  - pypiwin32==219
  - pyyaml==3.11
  - requests==2.8.1
  - requests-toolbelt==0.4.0
  - sphinx-rtd-theme==0.1.9
  - twine==1.6.3
  - watchdog==0.8.3

